### ISSUE TITLE
undefined error

### ISSUE THREAD

**Issue by tsuncp** [amcharts/export#6]
TypeError: Cannot read property '3' of undefined
    at Object.fabric.Color.getAlpha (http://localhost:9090/admin/bower_components/amcharts/plugins/export/libs/fabric.js/fabric.js:4559:30)
    at _setStrokeFillOpacity (http://localhost:9090/admin/bower_components/amcharts/plugins/export/libs/fabric.js/fabric.js:2920:55)
    at Object.extend.parseAttributes (http://localhost:9090/admin/bower_components/amcharts/plugins/export/libs/fabric.js/fabric.js:3571:14)
    at Function.fabric.Path.fromElement (http://localhost:9090/admin/bower_components/amcharts/plugins/export/libs/fabric.js/fabric.js:16020:35)
    at fabric.ElementsParser._createObject (http://localhost:9090/admin/bower_components/amcharts/plugins/export/libs/fabric.js/fabric.js:3873:11)
    at fabric.ElementsParser.createObject (http://localhost:9090/admin/bower_components/amcharts/plugins/export/libs/fabric.js/fabric.js:3860:12)
    at http://localhost:9090/admin/bower_components/amcharts/plugins/export/libs/fabric.js/fabric.js:3850:15

**Comment by tsuncp** [comment]
the problem is happened while guidelines are used in the charts

				            "guides": [{
				                "dashLength": 6,
				                "inside": true,
				                "label": "Yellow",
				                "lineAlpha": 1,
				                "value": 50,
				                "lineColor": "yellow"
				            },
                            {
                                "dashLength": 0,
                                "inside": true,
                                "label": "Green",
                                "lineAlpha": 1,
                                "value": 100,
                                "lineColor": "greenyellow"
                            }, {
                                "dashLength": 0,
                                "inside": true,
                                "label": "Red",
                                "lineAlpha": 1,
                                "value": 0,
                                "lineColor": "red"
                            }],

**Comment by maertz** [comment]
Please use hexadecimal color codes instead of "alias" names such as "greenyellow". Following page should help you finding the right colors: http://www.color-hex.com/

**Comment by tsuncp** [comment]
Ok thanks. But I think it should be mentioned in the document
