### ISSUE TITLE
Exception when trying to export a chart to PDF

### ISSUE THREAD

**Issue by arielvol** [amcharts/export#88]
Hi, 
I tried to activate the ExportMenu option in our amCharts. 
Whenever I try to export a chart to PDF, I get this error:

Uncaught (in promise) ChunkLoadError: Loading chunk vendors~pdfmake failed.
(error: http://localhost:8010/vendors~pdfmake.js)
    at Function.requireEnsure [as e] (http://localhost:9000/app.js:812:26)
    at Function.fn.e (http://localhost:9000/app.js:156:40)
    at eval (webpack-internal:///./node_modules/@amcharts/amcharts4/.internal/core/export/Export.js:94:45)
    at step (webpack-internal:///./node_modules/tslib/tslib.es6.js:120:23)
    at Object.eval [as next] (webpack-internal:///./node_modules/tslib/tslib.es6.js:101:53)
    at eval (webpack-internal:///./node_modules/tslib/tslib.es6.js:94:71)
    at new Promise (<anonymous>)
    at Module.__awaiter (webpack-internal:///./node_modules/tslib/tslib.es6.js:90:12)
    at _pdfmake (webpack-internal:///./node_modules/@amcharts/amcharts4/.internal/core/export/Export.js:89:59)
    at Export.get [as pdfmake] (webpack-internal:///./node_modules/@amcharts/amcharts4/.internal/core/export/Export.js:3626:34)
requireEnsure @ app.js:812
fn.e @ app.js:156
eval @ Export.js?7e9c:69
step @ tslib.es6.js?9ab4:99
eval @ tslib.es6.js?9ab4:80
eval @ tslib.es6.js?9ab4:73
__awaiter @ tslib.es6.js?9ab4:69
_pdfmake @ Export.js?7e9c:64
get @ Export.js?7e9c:3601
eval @ Export.js?7e9c:1792
step @ tslib.es6.js?9ab4:99
eval @ tslib.es6.js?9ab4:80
fulfilled @ tslib.es6.js?9ab4:70
Promise.then (async)
step @ tslib.es6.js?9ab4:72
eval @ tslib.es6.js?9ab4:73
__awaiter @ tslib.es6.js?9ab4:69
Export.export @ Export.js?7e9c:605
eval @ Export.js?7e9c:506
eval @ EventDispatcher.js?daec:380
eval @ EventDispatcher.js?daec:265
each @ Array.js?6e0f:74
EventDispatcher._eachListener @ EventDispatcher.js?daec:238
EventDispatcher.dispatchImmediately @ EventDispatcher.js?daec:263
eval @ ExportMenu.js?4c1f:299
eval @ EventDispatcher.js?daec:380
eval @ EventDispatcher.js?daec:265
each @ Array.js?6e0f:74
EventDispatcher._eachListener @ EventDispatcher.js?daec:238
EventDispatcher.dispatchImmediately @ EventDispatcher.js?daec:263
Interaction.handleHit @ Interaction.js?e243:1047
Interaction.handleUp @ Interaction.js?e243:1318
eval @ Interaction.js?e243:1263
eval @ Iterator.js?0357:57
eval @ List.js?f2c0:40
each @ Iterator.js?0357:56
Interaction.handleGlobalUp @ Interaction.js?e243:1259
Interaction.handleGlobalPointerUp @ Interaction.js?e243:767
eval @ Interaction.js?e243:288

anyone encountered this ?

**Comment by arielvol** [comment]
I think the exception is in out own code. sorry

**Comment by arielvol** [comment]
I found the issue in my code but now I get an exception when exporting to PDF

**Comment by arielvol** [comment]
repoen

**Comment by martynasma** [comment]
If it's still on, we'll need some way to reproduce it. Can you post your chart online somewhere?

**Comment by martynasma** [comment]
If this is for amCharts 4, please post your issue in proper repo:
https://github.com/amcharts/amcharts4/issues
